baseURL = "https://example.com"
languageCode = "en-us"
title = "My personal blog"
theme="archie"
copyright = "© sapienhwaker"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
        mode="toggle"
        useCDN=false

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/hajarepd/"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/sapienhwaker/"

[[params.social]]
name = "Facebook"
icon = "facebook"
url = "https://www.facebook.com/hajarepd"
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
