baseURL = "https://example.com"
languageCode = "en-us"
title = "My personal blog"
theme="archie"
copyright = "© sapienhwaker"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
        mode="toggle"
        useCDN=false

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/sapienhwaker/"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://github.com/athulcajay/"

[[params.social]]
name = "GitLab"
icon = "gitlab"
url = "https://gitlab.com/athul/"
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
